// 서비스 타입별 설정 정보
export const SERVICE_TYPES = {
  baby: {
    key: 'baby',
    name: '육아 일기 포토북',
    subtitle: '아이의 성장을 한 권의 책으로',
    description: '소중한 아이의 매일매일을 사진과 일기로 기록하고, 세상에 하나뿐인 성장 포토북으로 만들어 보세요.',
    icon: '👶',
    color: 'from-rose-100 to-pink-50',
    accentColor: '#E8837C',
    recommendedSpec: 'SQUAREBOOK_HC',
    templateCategory: 'baby',
    fields: [
      { key: 'babyName', label: '아이 이름', type: 'text', placeholder: '예) 하은이', required: true },
      { key: 'birthDate', label: '생년월일', type: 'date', required: true },
      { key: 'period', label: '기록 기간', type: 'select', options: ['1개월', '3개월', '6개월', '1년'], required: true },
      { key: 'message', label: '엄마/아빠의 한마디', type: 'textarea', placeholder: '아이에게 전하고 싶은 메시지를 적어주세요', required: false },
    ],
  },
  kindergarten: {
    key: 'kindergarten',
    name: '유치원 알림장 책',
    subtitle: '한 학기의 추억을 졸업 앨범으로',
    description: '매일 보내온 알림장과 활동 사진을 모아서 특별한 졸업 앨범을 만들어 보세요.',
    icon: '🏫',
    color: 'from-yellow-100 to-amber-50',
    accentColor: '#E5A832',
    recommendedSpec: 'SQUAREBOOK_HC',
    templateCategory: 'notice',
    fields: [
      { key: 'childName', label: '원아 이름', type: 'text', placeholder: '예) 김하은', required: true },
      { key: 'className', label: '반 이름', type: 'text', placeholder: '예) 해바라기반', required: true },
      { key: 'year', label: '학년도', type: 'select', options: ['2024', '2025', '2026'], required: true },
      { key: 'semester', label: '학기', type: 'select', options: ['1학기', '2학기', '전체'], required: true },
      { key: 'teacherName', label: '담임 선생님', type: 'text', placeholder: '예) 이선생님', required: false },
    ],
  },
  fairytale: {
    key: 'fairytale',
    name: 'AI 동화책',
    subtitle: '아이가 주인공인 세상에 하나뿐인 동화',
    description: '아이의 이름과 좋아하는 주제를 알려주세요. AI가 아이만을 위한 특별한 동화를 만들어 드려요.',
    icon: '🧚',
    color: 'from-violet-100 to-purple-50',
    accentColor: '#8B5CF6',
    recommendedSpec: 'SQUAREBOOK_HC',
    templateCategory: 'etc',
    fields: [
      { key: 'heroName', label: '주인공 이름', type: 'text', placeholder: '예) 하은이', required: true },
      { key: 'heroAge', label: '주인공 나이', type: 'select', options: ['3살', '4살', '5살', '6살', '7살', '8살'], required: true },
      { key: 'theme', label: '동화 주제', type: 'select', options: ['우주 탐험', '바다 속 모험', '숲속 친구들', '마법의 나라', '공룡 세계', '직접 입력'], required: true },
      { key: 'customTheme', label: '직접 입력한 주제', type: 'text', placeholder: '원하는 주제를 자유롭게 입력하세요', required: false, showWhen: { field: 'theme', value: '직접 입력' } },
      { key: 'moralLesson', label: '담고 싶은 교훈', type: 'text', placeholder: '예) 용기, 나눔, 우정', required: false },
    ],
  },
  travel: {
    key: 'travel',
    name: '여행 포토북',
    subtitle: '여행의 순간을 영원히 간직하세요',
    description: '여행 사진을 올려주세요. 날짜와 장소별로 자동 정리된 아름다운 포토북을 만들어 드립니다.',
    icon: '✈️',
    color: 'from-sky-100 to-blue-50',
    accentColor: '#3B82F6',
    recommendedSpec: 'SQUAREBOOK_HC',
    templateCategory: 'travel',
    fields: [
      { key: 'tripName', label: '여행 제목', type: 'text', placeholder: '예) 2025 제주도 가족 여행', required: true },
      { key: 'destination', label: '여행지', type: 'text', placeholder: '예) 제주도', required: true },
      { key: 'startDate', label: '출발일', type: 'date', required: true },
      { key: 'endDate', label: '도착일', type: 'date', required: true },
      { key: 'companions', label: '동행인', type: 'text', placeholder: '예) 가족, 친구 이름', required: false },
    ],
  },
  selfpublish: {
    key: 'selfpublish',
    name: '1인 출판 플랫폼',
    subtitle: '당신의 이야기를 세상에 전하세요',
    description: '글과 사진을 올려 나만의 책을 만들고 주문하세요. 에세이, 시집, 사진집 등 무엇이든 가능합니다.',
    icon: '📖',
    color: 'from-emerald-100 to-green-50',
    accentColor: '#059669',
    recommendedSpec: 'SQUAREBOOK_HC',
    templateCategory: 'etc',
    fields: [
      { key: 'bookTitle', label: '책 제목', type: 'text', placeholder: '예) 나의 첫 에세이', required: true },
      { key: 'authorName', label: '저자명', type: 'text', placeholder: '예) 홍길동', required: true },
      { key: 'genre', label: '장르', type: 'select', options: ['에세이', '시집', '사진집', '일러스트집', '기타'], required: true },
      { key: 'bookDescription', label: '책 소개', type: 'textarea', placeholder: '책에 대한 간략한 소개를 작성해주세요', required: false },
    ],
  },
  pet: {
    key: 'pet',
    name: '반려동물 성장 앨범',
    subtitle: '우리 아이의 특별한 순간들',
    description: '사랑하는 반려동물의 사진을 월별로 모아 세상에서 가장 귀여운 성장 앨범을 만들어 보세요.',
    icon: '🐾',
    color: 'from-orange-100 to-amber-50',
    accentColor: '#EA580C',
    recommendedSpec: 'SLIMALBUM_HC',
    templateCategory: 'album',
    fields: [
      { key: 'petName', label: '반려동물 이름', type: 'text', placeholder: '예) 뽀삐', required: true },
      { key: 'petType', label: '종류', type: 'select', options: ['강아지', '고양이', '토끼', '햄스터', '기타'], required: true },
      { key: 'petBreed', label: '품종', type: 'text', placeholder: '예) 말티즈, 코리안숏헤어', required: false },
      { key: 'adoptDate', label: '입양일 / 생일', type: 'date', required: false },
      { key: 'ownerMessage', label: '우리 아이에게 한마디', type: 'textarea', placeholder: '반려동물에게 전하고 싶은 메시지', required: false },
    ],
  },
};

// 판형 정보
export const BOOK_SPECS = {
  SQUAREBOOK_HC: {
    uid: 'SQUAREBOOK_HC',
    name: '고화질 스퀘어북',
    size: '243×248mm',
    cover: '하드커버',
    binding: 'PUR 무선철',
    pages: '24~130p',
    pageIncrement: 2,
    basePrice: 19800,
    pricePerIncrement: 500,
    description: '가장 범용적인 판형. 앨범, 일기장, 졸업앨범 등 다양한 용도에 적합합니다.',
  },
  LAYFLAT_HC: {
    uid: 'LAYFLAT_HC',
    name: '레이플랫북',
    size: '243×248mm',
    cover: '하드커버',
    binding: '레이플랫',
    pages: '16~46p',
    pageIncrement: 2,
    description: '180도 완전 펼침. 웨딩 앨범, 사진집에 적합합니다.',
  },
  SLIMALBUM_HC: {
    uid: 'SLIMALBUM_HC',
    name: '슬림앨범',
    size: '243×248mm',
    cover: '하드커버',
    binding: '슬림앨범',
    pages: '20~30p',
    pageIncrement: 2,
    description: '간결한 분량. 선물용, 소규모 앨범에 적합합니다.',
  },
};

// 주문 상태 매핑
export const ORDER_STATUS = {
  20: { key: 'PAID', label: '결제완료', color: 'blue' },
  30: { key: 'CONFIRMED', label: '제작확정', color: 'indigo' },
  40: { key: 'IN_PRODUCTION', label: '제작중', color: 'yellow' },
  50: { key: 'PRODUCTION_COMPLETE', label: '제작완료', color: 'green' },
  60: { key: 'SHIPPED', label: '발송완료', color: 'teal' },
  70: { key: 'DELIVERED', label: '배송완료', color: 'emerald' },
  80: { key: 'CANCELLED', label: '취소', color: 'red' },
  81: { key: 'CANCELLED_REFUND', label: '취소(환불)', color: 'red' },
};
